name: CI
on:
  push:
    branches-ignore:
      - master
    paths:
      - "*.json"
      - "packages/**"
      - .github/workflows/ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - cidrmate
          - datemate
          - emojimate
          - urlmate
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup ğŸ”§
        uses: actions/setup-node@v4
      - name: Clean Install ğŸ§¹
        run: |
          npm i --workspace @somethingmate/${{matrix.package}}
          npm ci --workspace @somethingmate/${{matrix.package}}
      - name: Build ğŸš§
        run: npm run build --workspace @somethingmate/${{matrix.package}}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - cidrmate
          - datemate
          - emojimate
          - shared
          - urlmate
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup ğŸ”§
        uses: actions/setup-node@v4
      - name: Clean Install ğŸ§¹
        run: |
          npm i --workspace @somethingmate/${{matrix.package}}
          npm ci --workspace @somethingmate/${{matrix.package}}
      - name: Test ğŸš¦
        run: npm test --workspace @somethingmate/${{matrix.package}}
