name: Build and Deploy
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: deployment
    strategy:
      fail-fast: false
      matrix:
        package:
          - cidrmate
          - datemate
          - emojimate
          - urlmate
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup ðŸ”§
        uses: actions/setup-node@v4
      - name: Clean Install ðŸ§¹
        run: |
          npm i --workspace @somethingmate/${{matrix.package}}
          npm ci --workspace @somethingmate/${{matrix.package}}
      - name: Build ðŸš§
        run: npm run build --workspace @somethingmate/${{matrix.package}}
      - name: Generate README
        env:
          README_PATH: "./packages/${{matrix.package}}/dist/README.md"
          PACKAGE_PATH: "./packages/${{matrix.package}}/package.json"
        run: |
          jq -r '"# \(.title)\n\n\(.description). Visit \(.url).\n\nCode is available at "' "$PACKAGE_PATH" > "$README_PATH"
          echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}." >> "$README_PATH"
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PAT }}
          repository-name: "evilmarty/${{matrix.package}}"
          branch: gh-pages
          folder: "./packages/${{matrix.package}}/dist"
          clean: true
